# Generated by Django 5.0.1 on 2024-01-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuneTracker', '0002_remove_artist_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='artist_covers/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='artist_profiles/'),
        ),
    ]
